apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: print-result
spec:
  workspaces:
    - name: source
  steps:
    - name: print
      image: tinyunshe/busybox:latest
      workingDir: $(workspaces.source.path)
      script: |
        echo $(results.ociContainerImageBuild-url.path)
